// <auto-generated />
using Auth.DataInfra.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auth.DataInfra.Migrations
{
    [DbContext(typeof(AuthenticationContext))]
    [Migration("20200618160050_Auth.DataInfra.DataContext.AuthenticationContextInitial")]
    partial class AuthDataInfraDataContextAuthenticationContextInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auth.DataInfra.Entity.AuthEntity", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoginIndex")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Email");

                    b.ToTable("LoginDetails");

                    b.HasData(
                        new
                        {
                            Email = "test@gmail.com",
                            LoginIndex = "06/29/2020 05:50",
                            Password = "pwd"
                        },
                        new
                        {
                            Email = "test@yahoo.com",
                            LoginIndex = "06/29/2020 05:50",
                            Password = "pwd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
